---
title: "Plane Simulation"
author: "Yuhan Wu"
date: "4/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(GA)
library(animation)
```

```{r}
set.seed(1)
plane1_sim <- tibble(sim = 1:5000, capacity = 195, passenger = sample(x = 100:195, size = 5000, replace = TRUE), perc_disable = sample(x = 1:10, size = 5000, replace = TRUE),passenger_disable = ceiling(passenger*perc_disable/100), group_number = sample(x = 1:5, size = 5000, replace = TRUE), group_size = sample(x = 1:5, size =5000, replace = TRUE), group_tot = group_number* group_size, group_perc = group_tot/passenger)

plane1_constant_result <- plane1_sim %>%
  mutate(plane1_const = passenger * passenger_disable * 1/group_perc * 1/group_number)%>%
  group_by(sim)%>%
  summarise(sim,plane1_const)
  
```

```{r}
plane1_sim%>%
  summarise(capacity, passenger, passenger_disable, group_number, group_size, group_tot)
  
```


```{r}
sd(plane1_constant_result$plane1_const)

plane1_constant_graph <- plane1_constant_result%>%
  arrange(desc(plane1_const))%>%
  mutate(ranking = 1:5000)

plane1_constant_graph%>%
  ggplot(aes(x = plane1_const))+
  geom_density(aes(y = after_stat(count)))+
  coord_cartesian(xlim = c(0, 100000))

mean(
  quantile(plane1_constant_result$plane1_const, probs = c(0.05, 0.95))
  )


```

